# Generated by Django 6.0.6 on 2026-06-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
