# Generated by Django 6.0.6 on 2026-06-30 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_reply_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('illegal', 'Illegal content'), ('harassment', 'Harassment / abuse'), ('off_topic', 'Off-topic / rule violation'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('reporter_id', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.reply')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.thread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
