# Generated by Django 6.0.6 on 2026-07-02 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_modlog_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_replies', to='board.reply'),
        ),
        migrations.AddField(
            model_name='thread',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
